"""Parser for the SNIIM results pages.

The markup is machine-generated by ASP.NET and has been stable for years, so
targeted regexes are both safe and much faster than a DOM parse (a single
product-year response can be 8 MB).

Two table shapes exist:

  Frutas y Hortalizas (8 columns)
    Fecha | Presentacion | Origen | Destino | Precio Min | Precio Max | Precio Frec | Obs.

  Granos Basicos (7 columns, no Presentacion)
    Fecha | Origen | Destino | Precio Min | Precio Max | Precio Frec | Obs.

Defensive posture
-----------------
Fields are assigned to columns by matching the header row, and a data row whose
cell count does not match the header is REJECTED and counted rather than parsed
positionally. That matters more than it sounds: `_RE_CELL` only sees <td> tags
carrying a double-quoted class attribute, so a single class-less or
differently-classed cell in the middle of a row would otherwise shift every
field to its right. The result would not look like corruption - "Caja de 10 kg."
parses as the number 10 and a date parses as its day - so prices would land in
the wrong columns as plausible values. Counting the rejects and surfacing them
via `run.py verify` is the only way that stays visible.

Likewise `parse_results` distinguishes "the server said there are no records"
from "we could not find a results table at all". The caller needs that to avoid
recording an error page as a legitimately empty period.
"""
from __future__ import annotations

import html
import math
import re
from dataclasses import dataclass, field
from datetime import date

# --- regexes ---------------------------------------------------------------
_RE_TABLE = re.compile(r'<table[^>]*id="tblResultados"[^>]*>(.*?)</table>', re.S | re.I)
_RE_GENERALES = re.compile(r'<table[^>]*id="tblDatosGenerales"[^>]*>(.*?)</table>', re.S | re.I)
_RE_ROW = re.compile(r"<tr[^>]*>(.*?)</tr>", re.S | re.I)
# Any <td>, with or without a class. Class is captured when present so rows can
# still be classified, but an unclassed cell is no longer invisible.
_RE_CELL = re.compile(r"<td([^>]*)>(.*?)</td>", re.S | re.I)
_RE_CLASS = re.compile(r'class\s*=\s*["\']?([^"\'>\s]*)', re.I)
_RE_TAG = re.compile(r"<[^>]+>")
_RE_WS = re.compile(r"\s+")
_RE_PAGINACION = re.compile(r'id="lblPaginacion"[^>]*>(.*?)</span>', re.S | re.I)
_RE_PAG_NUMS = re.compile(r"(\d+)\s*de\s*(\d+)")
_RE_RANGO = re.compile(r"Registros del\s*([\d/]*)\s*al\s*([\d/]*)")

# Number shapes we are willing to interpret. Anything else returns None rather
# than being guessed at, because a wrong guess is a 100x price error.
_RE_PLAIN = re.compile(r"^\d+(?:\.\d+)?$")                  # 58, 58.00
_RE_THOUSANDS = re.compile(r"^\d{1,3}(?:,\d{3})+(?:\.\d+)?$")  # 1,234.56
_RE_DECIMAL_COMMA = re.compile(r"^\d+,\d{1,2}$")             # 58,00
_RE_DMY = re.compile(r"^(\d{1,2})/(\d{1,2})/(\d{4})$")

NO_RECORDS_MARKERS = (
    "NO HAY REGISTROS",
    "No puede seleccionar todos los productos",
)

# Text that appears on ASP.NET error / maintenance pages. Seeing any of these
# means a 200 response is not a usable result.
ERROR_MARKERS = (
    "Server Error in",
    "Runtime Error",
    "Error de servidor en",
    "The resource you are looking for",
)


def _text(fragment: str) -> str:
    """Strip tags, unescape entities, collapse whitespace."""
    s = _RE_TAG.sub(" ", fragment)
    s = html.unescape(s)
    s = s.replace("\xa0", " ")
    return _RE_WS.sub(" ", s).strip()


def _num(fragment: str) -> float | None:
    """Parse a price cell.

    Conservative on purpose. SNIIM writes plain "58.00", but a locale flip to
    "58,00" or a thousands separator must not be silently misread - "58,00"
    naively comma-stripped becomes 5800.00, a 100x error that survives every
    downstream check. Unrecognised shapes return None.
    """
    s = _text(fragment)
    if not s or s in ("-", "--", "---", "N/D", "S/C", "n/d"):
        return None

    if _RE_PLAIN.match(s):
        raw = s
    elif _RE_THOUSANDS.match(s):
        raw = s.replace(",", "")
    elif _RE_DECIMAL_COMMA.match(s):
        raw = s.replace(",", ".")
    else:
        return None

    try:
        v = float(raw)
    except ValueError:
        return None
    if not math.isfinite(v):
        return None
    # SNIIM emits 0.00 as a placeholder for "not surveyed".
    return v if v > 0 else None


def _dmy(fragment: str) -> date | None:
    s = _text(fragment)
    m = _RE_DMY.match(s)
    if not m:
        return None
    d, mo, y = (int(x) for x in m.groups())
    try:
        return date(y, mo, d)
    except ValueError:
        return None


# --- column label -> canonical field --------------------------------------
_COLMAP = {
    "fecha": "fecha",
    "presentacion": "presentacion",
    "presentación": "presentacion",
    "origen": "origen",
    "destino": "destino",
    "precio min": "precio_min",
    "precio mín": "precio_min",
    "precio minimo": "precio_min",
    "precio mínimo": "precio_min",
    "precio max": "precio_max",
    "precio máx": "precio_max",
    "precio maximo": "precio_max",
    "precio máximo": "precio_max",
    "precio frec": "precio_frec",
    "precio frecuente": "precio_frec",
    "obs.": "obs",
    "obs": "obs",
    "observaciones": "obs",
}

# A results table is only usable if the header yielded these.
REQUIRED_FIELDS = {"fecha", "origen", "destino", "precio_min", "precio_max", "precio_frec"}


@dataclass
class ParseResult:
    rows: list[dict] = field(default_factory=list)
    producto: str | None = None
    calidad: str | None = None
    grupo_seen: list[str] = field(default_factory=list)
    page: int = 1
    pages: int = 1
    rango_inicio: date | None = None
    rango_fin: date | None = None
    no_records: bool = False
    rejected_reason: str | None = None
    # Structural signals the caller needs in order to tell "genuinely empty"
    # apart from "we failed to read this page".
    table_found: bool = False
    header: list[str] = field(default_factory=list)
    malformed_rows: int = 0
    error_page: bool = False

    @property
    def truncated(self) -> bool:
        """True when the server paginated, i.e. we did not get everything."""
        return self.pages > self.page

    @property
    def header_ok(self) -> bool:
        return REQUIRED_FIELDS.issubset(set(self.header))

    @property
    def usable(self) -> bool:
        """Did we successfully read a results table, even if it held no rows?"""
        return not self.error_page and (self.no_records or (self.table_found and self.header_ok))


def parse_results(document: str) -> ParseResult:
    """Parse one Resultados* HTML page into tidy row dicts."""
    res = ParseResult()

    # Query echo: which date range the server actually honoured. Used by the
    # caller as a guard against silently ignored parameters.
    m = _RE_RANGO.search(document)
    if m:
        res.rango_inicio = _dmy(m.group(1))
        res.rango_fin = _dmy(m.group(2))

    m = _RE_PAGINACION.search(document)
    if m:
        nums = _RE_PAG_NUMS.search(_text(m.group(1)))
        if nums:
            res.page, res.pages = int(nums.group(1)), int(nums.group(2))

    head = document[:4000]
    for marker in ERROR_MARKERS:
        if marker in head or marker in document[-4000:]:
            res.error_page = True
            res.rejected_reason = marker
            break

    mt = _RE_TABLE.search(document)
    res.table_found = mt is not None

    # Only scan the results table (plus the rejection banner area) for the
    # no-records markers, so unrelated page text cannot trip them.
    scan = _text(mt.group(1)) if mt else ""
    scan_full = _text(document) if not scan else scan + " " + _text(document)
    for marker in NO_RECORDS_MARKERS:
        if marker in scan_full:
            res.no_records = True
            res.rejected_reason = marker
            break

    # Product / quality header block.
    mg = _RE_GENERALES.search(document)
    if mg:
        vals = []
        for attrs, frag in _RE_CELL.findall(mg.group(1)):
            cm = _RE_CLASS.search(attrs)
            if cm and "DatTAB2" in cm.group(1):
                t = _text(frag)
                if t:
                    vals.append(t)
        if vals:
            res.producto = vals[0]
        if len(vals) > 1:
            res.calidad = vals[1]

    if not mt:
        return res

    grupo: str | None = None

    for rowm in _RE_ROW.finditer(mt.group(1)):
        cells = []
        for attrs, frag in _RE_CELL.findall(rowm.group(1)):
            cm = _RE_CLASS.search(attrs)
            cells.append((cm.group(1) if cm else "", frag))
        if not cells:
            continue
        classes = [c[0] for c in cells]

        # Header row.
        if any("titDATtab2" in c for c in classes):
            header = []
            for cls, frag in cells:
                if "titDATtab2" not in cls:
                    continue
                label = _text(frag).lower().rstrip(":")
                header.append(_COLMAP.get(label, f"?{label}"))
            res.header = header
            continue

        # Group separator row ("Frutas" / "Hortalizas").
        if any("encabACT2" in c for c in classes):
            grupo = _text(cells[0][1]) or None
            if grupo and grupo not in res.grupo_seen:
                res.grupo_seen.append(grupo)
            continue

        if not res.header:
            continue

        # Data row. Count every cell, not only the classed ones, so a shifted
        # row is detected instead of being silently misparsed.
        if len(cells) != len(res.header):
            # Tolerate trailing layout spacers with no class and no content.
            trimmed = list(cells)
            while len(trimmed) > len(res.header) and not trimmed[-1][0] and not _text(trimmed[-1][1]):
                trimmed.pop()
            if len(trimmed) != len(res.header):
                if any(_text(f) for _c, f in cells):
                    res.malformed_rows += 1
                continue
            cells = trimmed

        rec: dict = {"grupo": grupo}
        for idx, (_cls, frag) in enumerate(cells):
            field_name = res.header[idx]
            if field_name == "fecha":
                rec["fecha"] = _dmy(frag)
            elif field_name in ("precio_min", "precio_max", "precio_frec"):
                rec[field_name] = _num(frag)
            elif field_name.startswith("?"):
                continue  # unrecognised column - do not invent a field for it
            else:
                val = _text(frag)
                rec[field_name] = None if val in ("", "-", "--", "---") else val

        if rec.get("fecha") is None:
            # A data-looking row whose date will not parse is a red flag, not
            # something to drop quietly.
            if any(_text(f) for _c, f in cells):
                res.malformed_rows += 1
            continue
        res.rows.append(rec)

    return res


def parse_dropdown(document: str, name: str) -> list[tuple[str, str]]:
    """Extract (value, label) pairs from a named <select> on a Consulta page."""
    doc = re.sub(r"<script.*?</script>", "", document, flags=re.S | re.I)
    m = re.search(rf'<select[^>]*name="{re.escape(name)}"[^>]*>(.*?)</select>', doc, re.S | re.I)
    if not m:
        return []
    out = []
    for value, label in re.findall(r'<option[^>]*value="([^"]*)"[^>]*>([^<]*)', m.group(1)):
        out.append((value, _text(label)))
    return out
